apiVersion: v1
data:
  nginx.conf: |
    server {
      listen 8443 ssl;
      ssl_protocols TLSv1.2 TLSv1.1;
      ssl_prefer_server_ciphers on;
      ssl_session_cache   shared:SSL:10m;
      ssl_session_timeout 10m;
      ssl_certificate /etc/nginx/certs/certificato.crt;
      ssl_certificate_key /etc/nginx/certs/certificato.key;

     
      ssl_verify_client on;
      ssl_client_certificate /etc/nginx/ssl/apigw.crt;    
      ssl_verify_depth 3;
      
      underscores_in_headers on;
    
      location / {
        return 200 'Nginx is up and running';
        add_header Content-Type text/plain;
      }
    
      location /api/v1/conti/info/disponibilita {
        proxy_pass_request_headers on;
        proxy_pass http://tpm-router.offloading-mainframe-richieste-informative.svc.cluster.local:80;
      }
    }
    
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx.conf
  selfLink: /api/v1/namespaces/apigw-proxy-mutua/configmaps/nginx.conf
