apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nginx-secureproxy
  labels:
    app: secureproxy
    name: secureproxy
  annotations:
    "openshift.io/display-name": secureproxy
    description: |
      An Nginx solution for an OpenShift route securization - Throttling, authentication features for openshift ingress route. This is a tech preview feature.
    iconClass: icon-cogs
    tags: "secureproxy, nginx"
parameters:
- description: The location of the Nginx image
  name: IMAGE_NGINX
  value: sdpsvalmbf.rete.testposte:5000/globals/nginx-116-rhel7
- description: The service name for upstream
  name: NOME_SERVICE
  required: true
- description: The request limit per second
  name: REQUESTxSEC_LIMIT
  required: true
- description: The Burst size
  name: BURST
  required: true


objects:
- apiVersion: v1
  data:
    nginx.conf: |
      
      limit_req_zone $server_name zone=limite:10m rate=${REQUESTxSEC_LIMIT}r/s;
      log_format  datadog  '$time_local "$request_method $uri" $status $body_bytes_sent $request_time';

      server {
        listen 8443 ssl;
        ssl_protocols TLSv1.2 TLSv1.1;
        ssl_prefer_server_ciphers on;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_certificate /etc/nginx/certs/certificato.crt;
        ssl_certificate_key /etc/nginx/certs/certificato.key;
       
        underscores_in_headers on;
      
        location / {
          proxy_pass_request_headers on;
          limit_req zone=limite burst=${BURST};
          limit_req_status 408;
          proxy_pass http://${NOME_SERVICE}.svc.cluster.local:80;
        }
      }
      
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: nginx.conf
    selfLink: /api/v1/namespaces/apigw-proxy-mutua/configmaps/nginx.conf
        
- apiVersion: v1
  data:
    certificato.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUgrekNDQmVPZ0F3SUJBZ0lUSFFBQUxwWXh6NHZBT1ZGL0p3QURBQUF1bGpBTkJna3Foa2lHOXcwQkFRc0YKQURCRU1Sa3dGd1lLQ1pJbWlaUHlMR1FCR1JZSmRHVnpkSEJ2YzNSbE1SUXdFZ1lLQ1pJbWlaUHlMR1FCR1JZRQpjbVYwWlRFUk1BOEdBMVVFQXhNSVRHRmlVMVZDUTBFd0hoY05NVGt4TVRBM01EZ3lOVEl4V2hjTk1qRXhNVEEyCk1EZ3lOVEl4V2pDQmhERU5NQXNHQTFVRUNCTUVVbTl0WlRFTk1Bc0dBMVVFQnhNRVVtOXRaVEVlTUJ3R0ExVUUKQ2hNVlVHOXpkR1VnU1hSaGJHbGhibVVnVXk1d0xrRXVNUjR3SEFZRFZRUUxFeFZRYjNOMFpTQkpkR0ZzYVdGdQpaU0JUTG5BdVFTNHhKREFpQmdOVkJBTU1HeW91WVhCd0xuTjJhV3d5TG05amNISnRMblJsYzNSd2IzTjBaVENDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFEvNkgxbkQ4ekRlRTdhWURUNnVIencKZUxaSkEvMGZkUzZjM1hXekxtMEhzL0hKeEc3QlhBVWdRdlBGZ2lsWkFQaUUyZVJkemNVR3hDKyttd0JTMHFwbgo1c1hlZHFtbTVhSnNqbEZpYjR1VDFwUGpYNFVXOS91RVNCaHg0bm5vR20wYVAySUZNTWdpUG03SlNYaVI4ZHlzCmRHUWQvMEY4RU8zekZsdGs1dkFEa25OU3N4UUUyVVJ5eDNCT1gvckJYVGRTZDdQQzZaOXlwSnF2d3VvNFE1SFUKRnQyWTJHc0JNMXpjMnRDUjhRTWdDZmlUSjVDWVJjYUdsUVR5a0ZWNkpEOUhQMlNlenpwdDV1Y21kOEZzam50WQptb3BjT25iTlB3dEwyemtGbDNFbDNoTGZOTDJFd3B0WUJKblRkNFBKYlJqWkMvYjl2Tk52d2lpSjRNdkxiZFVDCkF3RUFBYU9DQTZNd2dnT2ZNQXNHQTFVZER3UUVBd0lGb0RBbUJnTlZIUkVFSHpBZGdoc3FMbUZ3Y0M1emRtbHMKTWk1dlkzQnliUzUwWlhOMGNHOXpkR1V3SFFZRFZSME9CQllFRkxNUi8wMGFQeTI4bWtFNFRncUw2YVc1ZHlEbgpNQjhHQTFVZEl3UVlNQmFBRkNna293cm0zTGErQUh5NE1ucmVkeEVPTmx6c01JSHlCZ05WSFI4RWdlb3dnZWN3CmdlU2dnZUdnZ2Q2R2diZHNaR0Z3T2k4dkwwTk9QVXhoWWxOVlFrTkJLRE1wTEVOT1BWTlFTMGxEUVRBeFZpeEQKVGoxRFJGQXNRMDQ5VUhWaWJHbGpKVEl3UzJWNUpUSXdVMlZ5ZG1salpYTXNRMDQ5VTJWeWRtbGpaWE1zUTA0OQpRMjl1Wm1sbmRYSmhkR2x2Yml4RVF6MWpiM0p3TEVSRFBYUmxjM1J3YjNOMFpUOWpaWEowYVdacFkyRjBaVkpsCmRtOWpZWFJwYjI1TWFYTjBQMkpoYzJVL2IySnFaV04wUTJ4aGMzTTlZMUpNUkdsemRISnBZblYwYVc5dVVHOXAKYm5TR0ltaDBkSEE2THk5d2EybDNaV0l5TDNCcmFTOU1ZV0pUVlVKRFFTZ3pLUzVqY213d2dnRjdCZ2dyQmdFRgpCUWNCQVFTQ0FXMHdnZ0ZwTUlHcUJnZ3JCZ0VGQlFjd0FvYUJuV3hrWVhBNkx5OHZRMDQ5VEdGaVUxVkNRMEVzClEwNDlRVWxCTEVOT1BWQjFZbXhwWXlVeU1FdGxlU1V5TUZObGNuWnBZMlZ6TEVOT1BWTmxjblpwWTJWekxFTk8KUFVOdmJtWnBaM1Z5WVhScGIyNHNSRU05WTI5eWNDeEVRejEwWlhOMGNHOXpkR1UvWTBGRFpYSjBhV1pwWTJGMApaVDlpWVhObFAyOWlhbVZqZEVOc1lYTnpQV05sY25ScFptbGpZWFJwYjI1QmRYUm9iM0pwZEhrd0t3WUlLd1lCCkJRVUhNQUtHSDJoMGRIQTZMeTl3YTJsM1pXSXlMM0JyYVM5TVlXSlRWVUpEUVM1amNuUXdPd1lJS3dZQkJRVUgKTUFLR0wyaDBkSEE2THk5cGJuUmpjbXd1Y0c5emRHVnBkR0ZzYVdGdVpTNXBkQzl3YTJrdlRHRmlVMVZDUTBFdQpZM0owTUI4R0NDc0dBUVVGQnpBQmhoTm9kSFJ3T2k4dmNHdHBkMlZpTWk5dlkzTndNQzhHQ0NzR0FRVUZCekFCCmhpTm9kSFJ3T2k4dmFXNTBZM0pzTG5CdmMzUmxhWFJoYkdsaGJtVXVhWFF2YjJOemNEQThCZ2tyQmdFRUFZSTMKRlFjRUx6QXRCaVVyQmdFRUFZSTNGUWlDbTZoOWdkK3ZQNEdOZ3d5RXhhOW9oS0wwQ29FUDhxSXVucTFxQWdGbQpBZ0VBTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Cc0dDU3NHQVFRQmdqY1ZDZ1FPTUF3d0NnWUlLd1lCCkJRVUhBd0V3UkFZSktvWklodmNOQVFrUEJEY3dOVEFPQmdncWhraUc5dzBEQWdJQ0FJQXdEZ1lJS29aSWh2Y04KQXdRQ0FnQ0FNQWNHQlNzT0F3SUhNQW9HQ0NxR1NJYjNEUU1ITUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCWAovWFd3eVpIdVp5Rm0zOStMWHVzcFpKTCtQeU5JcHNWdVhtK0xqL0NyNE5GQTY4ZDlDV0tDTStsbm44elJwRERrCldmWERha3NKRzhhMnB0UHg5c1l0bDFBVjdzRjZjMEo2MkNiMnIrUzVYR3JOOUhLQXI5MVV0WUhaVmFhSmdKZFYKK0FJUmk1MmJndldxVUMyWEROSXdIdVQ0bmtpb0xPQlJIWjFVODNKeHp3UWVQY2xhYXNxeEplRGtqS01aODRtdgpLbERzTDFLNkVjNDlkSk5SSlZCa01UOVZvRFRZOUR0aUhMeUdyVTU0Yk5hT2VrWU95RHNWTGVFaVhyY3ozTHk0CitqaXVOL0FtRitucWdXck1hMjhJaXFiVG9zdFgvZlZHY3JkdnlpeTFtamlGMGJIQTFRK093b21PVk1qaUVSZk8KanlWcG1yTG1pNnBqdGJjMVFFaVZKRDBPRWQxWkJ5SVA4dno4elNpQ1BuWCtXcW9HSjFJa05JeUcvUkJZNWZwTwpqMkYvN1ZxdTZLdk54Ny9JYXM3cVZiUEZKVjNxb01uMkxYL0l3SUlqaXNkZEVCUVVZbVB3b1RGVk5rMGVleDM5CmlHeThZRjYzNkhMV3ZOYkF3emdpTUtpZVNlUzlZaWovck1YeU4zb3crV0prSktHTm8vSGhhZUxybXJwS2xVblYKaHJDQ09qWWdxeTRkYldWOTNYUS9hb1VEamFNTjJaeTZhTWxJdmFUZWlUa1lzbmdBRFRoSWVaa1luWURta0VlZgpwRkJEMzFSb3BWOTlkVHo1dGIrMlN3ZXUyWUdENVM0SlJIVE9BTkZoTlNHb2hwcUF5SmV5RDFWMzNKL0dZREN3CkJVQStoUE0rclpSZFpjdHpUSFdYdFJjaHJWZHgyNyt6RVVvc2hlRVZSdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGcVRDQ0E1R2dBd0lCQWdJUUVoSmpBTnNBdzZ4Rk5meWZJZmRQbHpBTkJna3Foa2lHOXcwQkFRc0ZBREFVCk1SSXdFQVlEVlFRREV3bE1ZV0pTVDA5VVEwRXdIaGNOTVRZd09URXpNVFExTnpJeFdoY05Nell3T1RFek1UVXcKTnpFeVdqQVVNUkl3RUFZRFZRUURFd2xNWVdKU1QwOVVRMEV3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQwpEd0F3Z2dJS0FvSUNBUURiUkRVemplYWJrbmNES3JIdmE1b3VvNERuUnVlQTZLL25jcGhVL2lXbElBZldVMDZhCjF2dlJ4bVFiays3MTdabGp0MlBqeGk4YXdqVjN1YXljSy9XQ3d3eUhOTjYyQVdDYXdKM05rMk8zNmwxeHFPSzUKRktqS3g4ck82RVpmN2xCVTI5SHFFaUJ4MFNJQzJ2MlJFbVdPRUdTN3JCMkJFOCtOSTIvWHFsM0xUOGFPZEdjVQpIelk5NnpYT0E2QmNLOXNKV3dGS2Rja0lWZExBdUEvSEtHQXV0cFlheWpOaUlwVUUwYThWeXBzejZiYkp4TnhvClNmQlF3UTFPQy9HbDNHZHRwaDJ4TkZXei9GNjhyNC9xQTNoYnpQNEUzUU9LVzNEYSs4ZWc2bk1PZ3hmWStucDYKOVd3UCtoV2hXdWlRQktIOHVIMjhzamhEM1lEbXl6V1hZZmlCZ3VvVkVPbFcvWU9GdEp5dmR4d1N5cGFEeVhoMgpNZ05oNTdaK1dicS9iQ2l2Sksxank1d1hHS3NUMjJObXhENFIwLzg0clQvZE9MVTkxSis4Ym9IQTBLbDJSRjV6CnZ2NHlSaWhIdFdxenN3ZmJOeVZXcGZnNUxnUFdLNGFpMTY0SEsvdFpYRjZVaFVpVFJNdmZyUHRVZVp6Nm4wd3oKZ0RJemFsN0J2UUZtVkQ0Rmg3ZG5LWE5ENzAyU1l2MmFxblNXM0lTVFRZVFUxa2doblROZytqOFdHWFM3ZjIySwpkVU5HeGw1bUZVN3RybVVnSXB2VXJXM29qWGZDQ0Zmazd3QzlGMlZhaFJKN1l4aHpadmgxZG1wYlpKclk3SWRaCnFveG10YzlWN3lCVnVhVU1LdUJJVFFucWZlKytJOG5XNUxtbkppYTVveXE3WmdlZ2kvbjZMeCsvblFJREFRQUIKbzRIMk1JSHpNQXNHQTFVZER3UUVBd0lCaGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTUApEU3BteEQzdkNUdmJmZDNhY29PY3M3bk5GakFRQmdrckJnRUVBWUkzRlFFRUF3SUJBRENCb1FZRFZSMGdCSUdaCk1JR1dNSUdUQmdncUF3U0xMME5aQlRDQmhqQkNCZ2dyQmdFRkJRY0NBakEySGpRQVF3QnZBSElBY0FCdkFISUEKWVFCMEFHVUFJQUJRQUc4QWJBQnBBR01BZVFBZ0FGTUFkQUJoQUhRQVpRQnRBR1VBYmdCME1FQUdDQ3NHQVFVRgpCd0lCRmpSb2RIUndPaTh2ZDNkM0xuQnJhV3hoWWk1eVpYUmxMblJsYzNSd2IzTjBaUzlqWlhKMGMzWmpMM0J2CmJHbGplUzUwZUhRQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQnkxendXTyt5VS9lZ2xycFJIWVJzQ01aZXQKc3owL1ZKTUloR0h5L2JJTkNod1NzdHgxQU8raEttSWErQ1Ftam1PTC9ZczNReVFBNlBLWW8vM2l2NlY1cUVRbgp1MDdWVmVDekxod0xKaktVTFliWFZTZGV1WGhBdUxockJYTmNHU0g0TjBEN2VpckErS1BxbVhlcVp0b1lZYUk4CkxydnQ2b0tZUlJWWW5IVEd5YnZ5TVo3TkhXN1RmczBuTEx4MjVkeHBvSVl0SFgwSlJTaFRldWRWY0JoaDRkRSsKcWdlY1QxeVVndmpXdldvREpyM2tPQVlnTVlOMnRLTzBpNUxzcnRXZy9mNEJBUXkwMlZsMVEwYlZ3Y1VnclJhZgpDS0QyY1JLVVhMVzhIV0xYTWJjYkV4NTJvNEpLc2VrNEp4b2MvUzJ3L1pjaXVkV3dGVWVxMzI0bVN1U3huZURFCjJVTFJydm9KUFN1SFoxckd4Z0RkcXI2UDJUbC9Uc2lubmNFemtPSExCYTFzYk8xLzFlNytVYXNDeGJ0REJIcWIKaG5NWkcrWGJnNG5pVmg4ZktoWFV5ZmpRbzF6UTlRbXhma2U2eTVEWEppUmowdHllYnVTbnR2b25Na0paOE15MQpNdFhsTXg1eGo3L1pWbnJRQ0o1MHd6RmowbCtjU3R3REpOTHZuOTlsdkNGa3dnMTdnU3V6Tis1cEJZQmV3Z3dwClVaUjRxb1V5MFFPKzFaZVUxL2VrcDZBTnM3OVE0NCtOT1lDRFQ4TGMzemhXMVFNL3V2L0lLRGVFSzJEK2JhOEkKbGpzNWx6c0xVL21nSnFIaGJlVitrVng1U1Urc0J6QnQrNzhJdmsvQWlEQXRaWjdyK04xOW9lK3lZWldZSi9YMgpubitUNFpmcWRKT08wYkMwK2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlJQ1RDQ0JmR2dBd0lCQWdJVEpRQUFBQWw1NkNRaEcweUZDUUFBQUFBQUNUQU5CZ2txaGtpRzl3MEJBUXNGCkFEQVVNUkl3RUFZRFZRUURFd2xNWVdKU1QwOVVRMEV3SGhjTk1UWXhNVEUyTVRZMU5qUTVXaGNOTWpZeE1URTIKTVRjd05qUTVXakJFTVJrd0Z3WUtDWkltaVpQeUxHUUJHUllKZEdWemRIQnZjM1JsTVJRd0VnWUtDWkltaVpQeQpMR1FCR1JZRWNtVjBaVEVSTUE4R0ExVUVBeE1JVEdGaVUxVkNRMEV3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUNEd0F3Z2dJS0FvSUNBUUMzekpHR2Q0cXR2V1FWWFdFN1J1WGV4blJDdElMcE9mM2tQUGE3NDg5N3NQc2QKL0Jub3YyZWhqbE5lcEV6OEdQRE5rMzcrWWpjS0Q1Mk9YU2VuWDU0TElVL2MxaHZLa1ZwQmtCMUFPdHYvTTFuVAptbHQrbmxISnZlNGFVUnJhb05ZbVR6TndiaWNSZ1lyL2ZtSHM2ZjZKM2JKRXVjY3hLL1RoSE5zK3M1TFdQOXV6CkVMZVN0bldtZXloa2RyWEhpOGt1elUxZytVRFowM01ua0sxUDdFekp1Vk9yVnNMaWd6Zi9wODV0TGE0UEFnNlIKcWNSZVcrb3JDVzZFK0pOQ3RtWTV5U29oZkgvUWVlMCthVG8vYW5WRm5hM1F0M2hoSFUxRGhsNHVNUTNOajErTgpUalRQcW4rMWpURXNLejZ1bzN6ZmRvQzRWK1pMVXE1YUJ3d2EvMUVWUS83Nzl0QmVKS3ZrcXFwU0g0d0lOclF4Ck43cmtiaTlvL1p6VFJMVE9ka1Y2VEdLSTB3WnZlbjN3WFNJc3pJUVMzZTRKZWQ1WHkveHhXcmNER3dtWHliSEsKVUo4QkphWTRwYllGQXl5dDhUUzdlSDBRb2lXQ3cyMGZXNzRQakxCU0YvTk9CYzlENDJxcVNZWTRlcWJJYnZhLwpOdm9qdldFWFVuM1FaUGtPeE40Z0dTd3JRaHdkNEw2ZlFEVXFKMm9CLzVLejJES2FmU2pmcVFWWXZCNnRwU0F5CjUvZnA4N2N6NmtoK1BqYUVrTk1GQzZJaW9WM2hSZk1ncTJ2TGQzQTEwbHA0RjNCVnNXakVPSlJXK1ZLdTczQnAKRW5iREJQQVQ1WUNHU1VreWFQb2NFQXdGMmxKSm5UZWttVkNyOWdIQnBHWEJ4ZW4wYzdLckt2K3BEc1drQVFJRApBUUFCbzRJRElqQ0NBeDR3RWdZSkt3WUJCQUdDTnhVQkJBVUNBd01BQXpBakJna3JCZ0VFQVlJM0ZRSUVGZ1FVCllFRkZsRWt3ZDRsdmpzaURFYmZiNTZtV21xSXdIUVlEVlIwT0JCWUVGQ2drb3dybTNMYStBSHk0TW5yZWR4RU8KTmx6c01Ca0dDU3NHQVFRQmdqY1VBZ1FNSGdvQVV3QjFBR0lBUXdCQk1Bc0dBMVVkRHdRRUF3SUJoakFTQmdOVgpIUk1CQWY4RUNEQUdBUUgvQWdFQU1COEdBMVVkSXdRWU1CYUFGSThOS21iRVBlOEpPOXQ5M2RweWc1eXp1YzBXCk1JSUJNd1lEVlIwZkJJSUJLakNDQVNZd2dnRWlvSUlCSHFDQ0FScUdJR2gwZEhBNkx5OXdhMmwzWldJeUwzQnIKYVM5TVlXSlNUMDlVUTBFdVkzSnNoakJvZEhSd09pOHZhVzUwWTNKc0xuQnZjM1JsYVhSaGJHbGhibVV1YVhRdgpjR3RwTDB4aFlsSlBUMVJEUVM1amNteUdnY05zWkdGd09pOHZjbVYwWlM1MFpYTjBjRzl6ZEdVdlEwNDlUR0ZpClVrOVBWRU5CTEVOT1BWTlFTMGxCVXpBeFZpeERUajFEUkZBc1EwNDlVSFZpYkdsakpUSXdTMlY1SlRJd1UyVnkKZG1salpYTXNRMDQ5VTJWeWRtbGpaWE1zUTA0OVEyOXVabWxuZFhKaGRHbHZiaXhFUXoxamIzSndMRVJEUFhSbApjM1J3YjNOMFpUOWpaWEowYVdacFkyRjBaVkpsZG05allYUnBiMjVNYVhOMFAySmhjMlUvYjJKcVpXTjBRMnhoCmMzTTlZMUpNUkdsemRISnBZblYwYVc5dVVHOXBiblF3Z2dFdUJnZ3JCZ0VGQlFjQkFRU0NBU0F3Z2dFY01Dd0cKQ0NzR0FRVUZCekFDaGlCb2RIUndPaTh2Y0d0cGQyVmlNaTl3YTJrdlRHRmlVazlQVkVOQkxtTnlkREE4QmdncgpCZ0VGQlFjd0FvWXdhSFIwY0RvdkwybHVkR055YkM1d2IzTjBaV2wwWVd4cFlXNWxMbWwwTDNCcmFTOU1ZV0pTClQwOVVRMEV1WTNKME1JR3RCZ2dyQmdFRkJRY3dBb2FCb0d4a1lYQTZMeTl5WlhSbExuUmxjM1J3YjNOMFpTOUQKVGoxTVlXSlNUMDlVUTBFc1EwNDlRVWxCTEVOT1BWQjFZbXhwWXlVeU1FdGxlU1V5TUZObGNuWnBZMlZ6TEVOTwpQVU52Ym1acFozVnlZWFJwYjI0c1JFTTlZMjl5Y0N4RVF6MTBaWE4wY0c5emRHVS9ZMEZEWlhKMGFXWnBZMkYwClpUOWlZWE5sUDI5aWFtVmpkRU5zWVhOelBXTmxjblJwWm1sallYUnBiMjVCZFhSb2IzSnBkSGt3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dJQkFBVTNzcnBwRnJjV1AzZ0JRUGI2ZEU2MGZOZHBQUWtFR3JZWU1BN3lhOHJyK0tqVwo4MnBLTTRRNlVLaWFpVHNrN29oRlVDRE4wYXZlMmpUSkN1b2dLRWhDd1J1VmtWWHMvYXFlM2tXV1JxZ3FVN0phCjY0NkdmMUNaMitjbi85K3VBWDFiWldVNWI0akhmVTJEWHZmN0dLSmxsWUlhUGpYbXFNY2pMYm93RlRQRDFmUHQKa1VyQUExUnV1VklvWnpuNmx1TTJ6MGxybEFPN0Q4OC9tcnpDY2VNWFFpWSt5UkdDQ1cvOFprUmNDWldycTh5UApsRHovTnlIa1hta2gyek9qM01LRnVuT2pOdTRkNTN1bzBHNElUVWlDbk5qYzVDOW1aSTRtVDBSMUFoUERKaDNYCi92TEVuSG5UNlZuNGJ6TVpFMmlBYlRpREVMb0kyb2g0WFhDUmdIV0JjbTJFZjNRVWluakFzUmtPVzJGQ1lGYzEKb3M2MkNUWjdOSHFYMDB3V0s5OWxkaTFvNFd2dTNaYkFaN1Jjc1hoVjg4TnpHVGNVekh3QjhiTHFLem5QTHU4dApYUFJYT0NqZWlrY1J3b05oazVNUllnTEFKcC9oZVQ4RHB1OTFTV0JOSkgvTmpOQllmajBXTk5KUWxoQ2hLWmFhCllOL2FFTE0vYjJ5eEFwUWVGempmWGY0UUIyc1NvM2o5Q3RLUnRFaHUybGNaUmwrd1YxczVhZnBNUzFRU0o0b2kKTnFCQTRXZHNEUDBUdk1KclZpRFJxL3JvSE1FdVFPMEplK2NYLzdrRHlGN0F6cWFSUG5qbTZRM1hDLzFOMnVJZQpDYzdlQ1dkNlZHaVJlK0VPUm5JWDF3MzFTT0ZERlBRNk02Q1hGM2FRQUlqWlZTbzJJMllrZ0xOekFTN1cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    certificato.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzBQK2g5WncvTXczaE8KMm1BMCtyaDg4SGkyU1FQOUgzVXVuTjExc3k1dEI3UHh5Y1J1d1Z3RklFTHp4WUlwV1FENGhObmtYYzNGQnNRdgp2cHNBVXRLcVorYkYzbmFwcHVXaWJJNVJZbStMazlhVDQxK0ZGdmY3aEVnWWNlSjU2QnB0R2o5aUJURElJajV1CnlVbDRrZkhjckhSa0hmOUJmQkR0OHhaYlpPYndBNUp6VXJNVUJObEVjc2R3VGwvNndWMDNVbmV6d3VtZmNxU2EKcjhMcU9FT1IxQmJkbU5ockFUTmMzTnJRa2ZFRElBbjRreWVRbUVYR2hwVUU4cEJWZWlRL1J6OWtuczg2YmVibgpKbmZCYkk1N1dKcUtYRHAyelQ4TFM5czVCWmR4SmQ0UzN6UzloTUtiV0FTWjAzZUR5VzBZMlF2Mi9ielRiOElvCmllREx5MjNWQWdNQkFBRUNnZ0VBQXgwSGV3TUl0dFM1ZzBNcVhqL21aK0lQYzdhWEp3d2dEZ29QbVRUYkhHOEIKb0srSGdSSTk4S2k1LzFQdUI2RE43M3o3OW9IWVNBcng0SkUrUkNjcUZGOXZFUVBpc05OOUsrME1HRVBIQVhZdwpRcVd1eExHODNzOU9IMzM0RjNyMjJlT1dMSzlDUkhLeStWN29zZmh6WVFocGlrRXFZNHN0RDY4Zk43enFjRUxZCkUvb2ZxbzFYM3kzNnpIelI1bnVXTUUwV1RKK1F1cks4RlpNN21vSlZMandlN1RUQzBaSWV5b0tPVkV6UmxKaU0KamYveWI2TmI3NEJCVkp4UUR4eVplOU1WMTZFY1FaK2lEWXF4V1MwQzAya2MzcmlNc2JvVGM4VHhxZ3djV04xZApQK1N3VjVFZDZRS1FSU3FoSlViWmkzSEZweUVxNHlCRDk5YSttSWtEa1FLQmdRRHN6RHNhZ1E5ejZ3YXJpeEdyCmIyaHQwNzIzZVVveDhVS2lCMWNvS1hFbHN1Z1ZpUlBJcTVramZieG9vNktGa0JFZjhsc3ZmU0hXVnpMWVhMOFYKMTM1dnVJbXp2STJmcm85dTBKMW1XZFFyTHdqZUxRSGpjTFA4L2t0T0ZTZ1B2TTRiaG8wS2lMeGVyMUpNb3drdgpnLzFoQWREKzl4UHZHY1U4ZmxPMnA1TXN6d0tCZ1FEQzNjWkRZN0VBMGpnWmh6N2hCdkRCUjdQUzFvdG9lQWg3CnVKYkJRYkpobGtLVllpakprUTlVZW1tSFBXa2RWYUV5dUU5ajBRVjFIc1p1cW9zU21CRkg0Ukl6VEFrUit5aTQKREdxUUU5Yk44ZDJ4akJJYXprcStkNmVUczB0WldYOFZmSUVtaDZ6cklVbEdDOWc3V3lsOHBUVUlSZFZ5UzM5TwpkZ2xKOXhRTUd3S0JnUUM3eEVwTmZ1OUE3S2x5VnlrZ3RvdXBJdEI1N3Z4dFU3Q1JpSjZNNHllc1RBd0tINU1ICmVVSktTVWFmOXJsRmpYSjIwWmVLdFgraVZheWtzZzUzaEZQbXhQNnovaHlTOVRrWkZ1VG9wdXc5ZmVOYlFYY1EKNFdwbmYwRTVYajlSRTFhZnJ2YWgxc0QvbDZmN3l2L2FwSi9EVDB4cEVJVEhBTGxNZWFOcDM4RXRNd0tCZ0ZaYwpuWUsrU3ZMM045K3dmZUNUQjk1UkhkUWlPM1NZUmdJM0E3RXdvWkw0V2hnRWdka2JUZlQ5cjRrOVlUbWIrcTRVCjJ6SjhyM09CcVNYZ3RYUVBLeEYxSVhEVWtPeUVLRDZ4V2dUeWxlOTk4dWUrRVVRS0N6d3dvWGNuTGd5eVNrMUcKZWFLTzNNYjBZSm9IbzlSaWlaZHhUSGlYSW9yZUJOVE1JVC9EbmdIakFvR0Fad1Y2KzhaWXpiK01UREt4TFAvOAoyOE5zbnI4aE5tY2VkdUowSDhHUzZJSHRMN1BFNnpYV09IdURtMzN4WTFQbTZxZGZjU1pLWFpyN1AyUldtZnFECnJQSVV3dHQ2QUFUZnM5VGY5Ymx1Vm9Bc3BxbGhsRGxOUG5lcHVPeTZlWXRvdFI1cTRINUg4RDZzWk80TUlDMzMKWWpZVTFTdEg4bmdvSEtTUm1kanR6aEU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  kind: Secret
  metadata:
    creationTimestamp: null
    name: certificatissl
    selfLink: /api/v1/namespaces/apigw-proxy-mutua/secrets/certificatissl
  type: Opaque

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: reverseproxy
    name: reverseproxy
    selfLink: /apis/apps.openshift.io/v1/namespaces/apigw-proxy-mutua/deploymentconfigs/reverseproxy
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: reverseproxy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: reverseproxy
          deploymentconfig: reverseproxy
      spec:
        containers:
        - image: ${IMAGE_NGINX}
          imagePullPolicy: Always
          name: reverseproxy
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/app-root/etc/nginx.d/
            name: nginxconf
            readOnly: true
          - mountPath: /etc/nginx/certs
            name: certificatissl
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: nginx.conf
          name: nginxconf
        - name: certificatissl
          secret:
            defaultMode: 420
            secretName: certificatissl
    test: false
    triggers:
    - type: ConfigChange
